name: Build Ladybird for Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: Build from LadybirdBrowser/ladybird
    runs-on: windows-latest

    steps:
    - name: Clone Ladybird official repo
      run: |
        git clone https://github.com/LadybirdBrowser/ladybird.git
        cd ladybird
        git submodule update --init --recursive

    - name: Install dependencies via Chocolatey
      run: |
        choco install -y cmake ninja git llvm make perl nasm

    - name: Add LLVM to PATH
      shell: powershell
      run: echo "C:\Program Files\LLVM\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Configure the build
      working-directory: ladybird
      run: |
        cmake -S Meta/Ladybird -B build -G Ninja ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_C_COMPILER=clang ^
          -DCMAKE_CXX_COMPILER=clang++

    - name: Build Ladybird
      working-directory: ladybird
      run: cmake --build build --target Ladybird

    - name: Find the Ladybird executable
      id: find_exe
      working-directory: ladybird
      shell: powershell
      run: |
        $exe = Get-ChildItem -Path build -Recurse -Filter "Ladybird.exe" | Select-Object -First 1
        if (-not $exe) { throw "Ladybird.exe not found." }
        echo "exe_path=$($exe.FullName)" >> $env:GITHUB_OUTPUT

    - name: Upload Ladybird executable
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ladybird-windows
        path: ${{ steps.find_exe.outputs.exe_path }}