name: Build Ladybird on Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies via Chocolatey
      run: |
        choco install -y cmake ninja git llvm make perl nasm

    - name: Add LLVM to PATH
      run: |
        echo "C:\Program Files\LLVM\bin" >> $GITHUB_PATH

    - name: Configure build with CMake
      run: |
        cmake -S . -B build -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_C_COMPILER=clang `
          -DCMAKE_CXX_COMPILER=clang++

    - name: Build the project
      run: cmake --build build --config Release

    - name: Find executable
      id: find_exe
      run: |
        $exe = Get-ChildItem -Recurse -Filter "*.exe" | Where-Object { $_.FullName -like "*ladybird*" } | Select-Object -First 1
        echo "Found exe: $($exe.FullName)"
        echo "exe_path=$($exe.FullName)" >> $env:GITHUB_OUTPUT

    - name: Upload built executable
      uses: actions/upload-artifact@v3
      with:
        name: ladybird-windows
        path: ${{ steps.find_exe.outputs.exe_path }}